Version-Integre/src/Entity/ReservationVoyage.php
<?php

namespace App\Entity;

use App\Repository\ReservationVoyageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=ReservationVoyageRepository::class)
 */
class ReservationVoyage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=true,onDelete="CASCADE")
     * @Groups("post:read")
     */
    private $Client;

    /**
     * @ORM\ManyToOne(targetEntity=Voyage::class)
     * @ORM\JoinColumn(nullable=true)
     * @Groups("post:read")
     */
    private $Voyage;

    /**
     * @ORM\Column(type="date",nullable=true)
     * @Groups("post:read")
     */
    private $Date_Reservation;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
         * @Assert\Choice({"Economy class", "First class", "Business class"})
     * @Groups("post:read")
     */
    private $Travel_Class;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 2,
     *      minMessage = "Votre Age doit être au moins 9 ans",
     *      maxMessage = "Votre Age ne peut pas etre plus 99 ans"
     * )
     * @Groups("post:read")
     */
    private $Age;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?User
    {
        return $this->Client;
    }

    public function setClient(?User $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getVoyage(): ?Voyage
    {
        return $this->Voyage;
    }

    public function setVoyage(?Voyage $Voyage): self
    {
        $this->Voyage = $Voyage;

        return $this;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->Date_Reservation;
    }

    public function setDateReservation(\DateTimeInterface $Date_Reservation): self
    {
        $this->Date_Reservation = $Date_Reservation;

        return $this;
    }

    public function getTravelClass(): ?string
    {
        return $this->Travel_Class;
    }

    public function setTravelClass(string $Travel_Class): self
    {
        $this->Travel_Class = $Travel_Class;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): self
    {
        $this->Age = $Age;

        return $this;
    }
}

Version-Integre/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields = {"Email"},message ="L'email que vous avez indiqué est déja utilisé !")
 */
class User implements UserInterface
{
     /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     * @Groups("post:read")
     */
    private $CIN;


    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(
     *      min = 2,
     *      max = 10,
     *      minMessage = "Votre Nom doit être au moins {{ limit }} characters long",
     *      maxMessage = "Votre Nom ne peut pas dépasser {{ limit }} characters"
     * )
     * @Groups("post:read")
     */
    private $UserName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank
     * @Assert\Positive
     * @Assert\Length(
     *      min = 4,
     *      max = 8,
     *      minMessage = "Votre Numero doit être au moins {{ limit }} characters long",
     *      maxMessage = "Votre Numero ne peut pas dépasser {{ limit }} characters"
     * )
     * @Groups("post:read")
     */
    private $Numero;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email.",  )
     * @Groups("post:read")
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("post:read")
     */
    private $Adresse;
    
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = "8", minMessage="Votre mot de passe doit faire minimum 8 carractéres")
     * @Groups("post:read")
     */
    private $Password;

    /**
     *  @Assert\EqualTo(propertyPath="Password", message="Vous n'avez pas tapé le méme mot de passe")
     * @Groups("post:read")
     */
    public $confirm_password;

    /**
     * @ORM\Column(type="json", nullable=true)
     * @Groups("post:read")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("post:read")
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("post:read")
     */
    private $reset_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("post:read")
     */
    private $Image;

    public function __toString()
    {
        return (string) $this->CIN;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCIN(): ?int
    {
        return $this->CIN;
    }

    public function setCIN(int $CIN): self
    {
        $this->CIN = $CIN;

        return $this;
    }




    public function getNumero(): ?int
    {
        return $this->Numero;
    }

    public function setNumero(?int $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    /**
     * Get the value of Password
     */ 
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * Set the value of Password
     *
     * @return  self
     */ 
    public function setPassword($Password)
    {
        $this->Password = $Password;

        return $this;
    }

    /**
     * Get min = 2,
     */ 
    public function getUserName()
    {
        return $this->UserName;
    }

    /**
     * Set min = 2,
     *
     * @return  self
     */ 
    public function setUserName($UserName)
    {
        $this->UserName = $UserName;

        return $this;
    }

    public function eraseCredentials() {
        
    }
     public function getSalt() {
        
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRoles(string $roles): self
    {
        if (is_array($this->roles)) {
            if (!in_array($roles, $this->roles, true)) {
                $this->roles[] = $roles;
            }
        }

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

Version-Integre/src/Form/ReservationVoyageType.php
<?php

namespace App\Form;

use App\Entity\ReservationVoyage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationVoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Date_Reservation',ChoiceType::class,[
                'choices' => [
                    'now' => new \DateTime('now'),
                    'tomorrow' => new \DateTime('+1 day'),
                    '1 week' => new \DateTime('+1 week'),
                    '1 month' => new \DateTime('+1 month'),
                ],
                'group_by' => function($choice, $key, $value) {
                    if ($choice <= new \DateTime('+3 days')) {
                        return 'Soon';
                    }

                    return 'Later';
                },
            ])
            ->add('Travel_Class',ChoiceType::class, [
                'choices' => [
                    'Economy class' => 'Economy class',
                    'First class' => 'First class',
                    'Business class' => 'Business class',
                ]])
            ->add('Age',null, [
                'attr' => [
                    'placeholder' => 'Age',
                ]])
            ->add('Client')
            ->add('Voyage')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ReservationVoyage::class,
        ]);
    }
}

Version-Integre/templates/reservation_voyage/TreResrvationVoyage.html.twig
{% extends 'Front/front.html.twig' %}

{% block title %}ReservationVoyage index{% endblock %}

{% block body %}
    <div id="main">
        <!-- Post -->
        <section class="post">
            <header class="major">
                <fieldset>
                    <div class="colums">

                        <h1>ReservationVoyage index</h1>
                        <div id="wrap">
                            <ul class="navbar">
                                <li>
                                    <a href="{{ path('reservation_voyage_index')}}">Actualiser</a>
                                </li>
                                <li>
                                    <a href="#">Trie</a>
                                    <ul>
                                        <li><a href="{{ path('order_By_Date_desc')}}">Trie par Date order Desc</a></li>
                                        <li><a href="{{ path('order_By_Date_ASC')}}">Trie par Date order Asc</a></li>>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Travel_Class</a>
                                    <ul>
                                        <li><a href="{{ path('Economy')}}">Economy</a></li>
                                        <li><a href="{{ path('Business')}}">Business</a></li>
                                        <li><a href="{{ path('First')}}">First</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Categories d'âge</a>
                                    <ul>
                                        <li><a href="{{ path('Enfants')}}">Enfants</a></li>
                                        <li><a href="{{ path('Adolescents')}}">Adolescents</a></li>
                                        <li><a href="{{ path('Adultes')}}">Adultes</a></li>
                                        <li><a href="{{ path('Aines')}}">Aines</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="btn btn-success" href="{{path('PDF_Reserver') }}">  PDF </a>
                                    <script type="text/javascript">
                                        function imprimer_page(){
                                            window.print();
                                        }
                                    </script>
                                </li>
                            </ul>
                        </div>
                        <form>
                            <input id="impression" class="js-programmatic-set-val btn btn-outline-primary mr-1 mb-1s" name="impression" type="button" onclick="imprimer_page()" value="Print this page" />
                        </form>
                        <table class="table">
                            <tr>
                                <th>Id</th>
                                <th>Voyage</th>
                                <th>Date_Reservation</th>
                                <th>Travel_Class</th>
                                <th>Age</th>
                                <th>actions</th>
                            </tr>
                            {% for reservation_voyage in reservation_voyages %}
                            <tbody>
                            <tr>
                                <td>{{ reservation_voyage.id }}</td>
                                {% if reservation_voyage.voyage.image|length > 0 %}
                                    <td><img src="{{ asset('uploads/'~ reservation_voyage.voyage.image ) }}" width="250" height="150"></td>
                                {% else %}
                                    <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="250" height="150"></td>
                                {% endif %}
                                <td>{{ reservation_voyage.DateReservation ? reservation_voyage.DateReservation|date('Y-m-d') : '' }}</td>
                                <td>{{ reservation_voyage.TravelClass }}</td>
                                <td>{{ reservation_voyage.Age }}</td>
                                <td>
                                    <a href="{{ path('reservation_voyage_show', {'id': reservation_voyage.id}) }}">show</a>
                                    <a href="{{ path('reservation_voyage_edit', {'id': reservation_voyage.id}) }}">edit</a>
                                </td>
                            </tr>
                            </tbody>
                            {% else %}
                                <tr>
                                    <td colspan="5">no records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>

                        <a href="{{ path('reservation_voyage_new') }}">Resrver New Voyage</a>

        </section>

    </div>

{% endblock %}

Version-Integre/templates/reservation_voyage/_delete_form.html.twig
<form method="post" action="{{ path('reservation_voyage_delete', {'id': reservation_voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation_voyage.id) }}">
    <button class="btn">Delete</button>
</form>

Version-Integre/templates/reservation_voyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Version-Integre/templates/reservation_voyage/edit.html.twig
{% extends 'Front/front.html.twig' %}

{% block title %}Edit ReservationVoyage{% endblock %}

{% block body %}

    <div id="main">
        <!-- Post -->
        <section class="post">
            <header class="major">
                <span class="date">Create new ReservationVoyage</span>
            </header>

            <div class="section-content">
                {{ form_start(form , {'attr': {'class':'form-horizontal','novalidate':'novalidate'}} ) }}
                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Client, {'label':'Votre CIN' ,'attr':{'placeholder': 'CIN...'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Voyage, {'attr':{'placeholder': 'Voyage'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Date_Reservation, {'attr':{'placeholder': 'numero...'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Travel_Class, {'label':'Email de clien' ,'attr':{'placeholder': 'Adresse email....'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Age, {'attr':{'placeholder': 'Votre Age'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        <button type= "submit" class="btn btn-success"> Reserver ! </button>
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>

                        <a href="{{ path('reservation_voyage_index') }}">back to list</a>
                    </fieldset>
                </div>

                {{ form_end(form) }}
                {{ include('reservation_voyage/_delete_form.html.twig') }}

            </div>
        </section>
    </div>
{% endblock %}

Version-Integre/templates/reservation_voyage/index.html.twig
{% extends 'Front/front.html.twig' %}

{% block title %}ReservationVoyage index{% endblock %}

{% block body %}
    <div id="main">
        <!-- Post -->
        <section class="post">
            <header class="major">
                <fieldset>
                    <div class="colums">

                        <h1>ReservationVoyage index</h1>
                        <div id="wrap">
                            <ul class="navbar">
                                <li>
                                    <a href="{{ path('reservation_voyage_index')}}">Actualiser</a>
                                </li>
                                <li>
                                    <a href="#">Trie</a>
                                    <ul>
                                        <li><a href="{{ path('order_By_Date_desc')}}">Trie par Date order Desc</a></li>
                                        <li><a href="{{ path('order_By_Date_ASC')}}">Trie par Date order Asc</a></li>>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Travel_Class</a>
                                    <ul>
                                        <li><a href="{{ path('Economy')}}">Economy</a></li>
                                        <li><a href="{{ path('Business')}}">Business</a></li>
                                        <li><a href="{{ path('First')}}">First</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Categories d'âge</a>
                                    <ul>
                                        <li><a href="{{ path('Enfants')}}">Enfants</a></li>
                                        <li><a href="{{ path('Adolescents')}}">Adolescents</a></li>
                                        <li><a href="{{ path('Adultes')}}">Adultes</a></li>
                                        <li><a href="{{ path('Aines')}}">Aines</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a class="btn btn-success" href="{{path('PDF_Reserver') }}">  PDF </a>
                                    <script type="text/javascript">
                                        function imprimer_page(){
                                            window.print();
                                        }
                                    </script>
                                </li>
                            </ul>
                        </div>
                        <form>
                            <input id="impression" class="js-programmatic-set-val btn btn-outline-primary mr-1 mb-1s" name="impression" type="button" onclick="imprimer_page()" value="Print this page" />
                        </form>
                        <table class="table">
                            <tr>
                                <th>Id</th>
                                <th>Voyage</th>
                                <th>Date_Reservation</th>
                                <th>Travel_Class</th>
                                <th>Age</th>
                                <th>actions</th>
                            </tr>
                            {% for reservation_voyage in reservation_voyages %}
                            <tbody>
                            <tr>
                                <td>{{ reservation_voyage.id }}</td>
                                {% if reservation_voyage.voyage.image|length > 0 %}
                                    <td><img src="{{ asset('uploads/'~ reservation_voyage.voyage.image ) }}" width="250" height="150"></td>
                                {% else %}
                                    <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="250" height="150"></td>
                                {% endif %}
                                <td>{{ reservation_voyage.DateReservation ? reservation_voyage.DateReservation|date('Y-m-d') : '' }}</td>
                                <td>{{ reservation_voyage.TravelClass }}</td>
                                <td>{{ reservation_voyage.Age }}</td>
                                <td>
                                    <a href="{{ path('reservation_voyage_show', {'id': reservation_voyage.id}) }}">show</a>
                                    <a href="{{ path('reservation_voyage_edit', {'id': reservation_voyage.id}) }}">edit</a>
                                </td>
                            </tr>
                            </tbody>
                            {% else %}
                                <tr>
                                    <td colspan="5">no records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                        <div class="align-center"> {{ knp_pagination_render(reservation_voyages) }}</div>

                        <a href="{{ path('reservation_voyage_new') }}">Resrver New Voyage</a>

        </section>

    </div>

{% endblock %}

Version-Integre/templates/reservation_voyage/new.html.twig
{% extends 'Front/front.html.twig' %}

{% block title %}New ReservationVoyage{% endblock %}

{% block body %}

    <div id="main">
        <!-- Post -->
        <section class="post">
            <header class="major">
                <span class="date">Create new ReservationVoyage</span>
            </header>

            <div class="section-content">
                {{ form_start(form , {'attr': {'class':'form-horizontal','novalidate':'novalidate'}} ) }}
                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Client, {'label':'Votre CIN' ,'attr':{'placeholder': 'CIN...'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Voyage, {'attr':{'placeholder': 'Voyage'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Date_Reservation, {'attr':{'placeholder': 'numero...'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Travel_Class, {'label':'Email de clien' ,'attr':{'placeholder': 'Adresse email....'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        {{ form_row(form.Age, {'attr':{'placeholder': 'Votre Age'}}) }}
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        <button type= "submit" class="btn btn-success"> Reserver ! </button>
                    </fieldset>
                </div>

                <div class="col-md-12">
                    <fieldset>
                        <a href="{{ path('reservation_voyage_index') }}">back to list</a>
                    </fieldset>
                </div>

                {{ form_end(form) }}

            </div>
        </section>
    </div>
{% endblock %}

Version-Integre/templates/reservation_voyage/pdf.html.twig
<h1 class="align-center">Bienvenue dans votre application Travel me </h1>

<p>Voila la liste de tout les Reservation des Voyages</p>

<table class="table" border="5">
    <tr>
        <th>Id</th>
        <th>Voyage</th>
        <th>Date_Reservation</th>
        <th>Travel_Class</th>
        <th>Age</th>
        <th>actions</th>
    </tr>
    {% for reservation_voyage in reservation_voyages %}
        <tbody>
        <tr>
            <td>{{ reservation_voyage.id }}</td>
            {% if reservation_voyage.voyage.image|length > 0 %}
                <td><img src="{{ asset('uploads/'~ reservation_voyage.voyage.image ) }}" width="250" height="150"></td>
            {% else %}
                <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="250" height="150"></td>
            {% endif %}
            <td>{{ reservation_voyage.DateReservation ? reservation_voyage.DateReservation|date('Y-m-d') : '' }}</td>
            <td>{{ reservation_voyage.TravelClass }}</td>
            <td>{{ reservation_voyage.Age }}</td>
        </tr>
        </tbody>
    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </tbody>

</table>

Version-Integre/templates/reservation_voyage/show.html.twig
{% extends 'Front/front.html.twig' %}

{% block title %}ReservationVoyage{% endblock %}

{% block body %}
<div id="main">
    <!-- Post -->
    <section class="post">
        <header class="major">
            <fieldset>
                <div class="colums">
                    <script type="text/javascript">
                        function imprimer_page(){
                            window.print();
                        }
                    </script>
                <form>
                    <input id="impression" class="js-programmatic-set-val btn btn-outline-primary mr-1 mb-1s" name="impression" type="button" onclick="imprimer_page()" value="Print this page" />
                </form>
    <h1>ReservationVoyage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation_voyage.id }}</td>
            </tr>
            <tr>
                <th>Voyage</th>
                {% if reservation_voyage.voyage.image|length > 0 %}
                    <td><img src="{{ asset('uploads/'~ reservation_voyage.voyage.image ) }}" width="450" height="250"></td>
                {% else %}
                    <td><img src="{{ asset('uploads/'~ "Not found.jpg" ) }}" width="250" height="150"></td>
                {% endif %}            </tr>
            <tr>
                <th>Client</th>
                <td>{{ reservation_voyage.Client.UserName }}</td>
            </tr>
            <tr>
                <th>Date_Reservation</th>
                <td>{{ reservation_voyage.DateReservation ? reservation_voyage.DateReservation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Travel_Class</th>
                <td>{{ reservation_voyage.TravelClass }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ reservation_voyage.Age }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_voyage_index') }}">back to list</a>

    <a href="{{ path('reservation_voyage_edit', {'id': reservation_voyage.id}) }}">edit</a>

    {{ include('reservation_voyage/_delete_form.html.twig') }}

    </section>
    <iframe style="border:0; width: 100%; height: 350px;" class="img-fluid" src="https://maps.google.com/maps?q=+{{reservation_voyage.voyage.NomVoyage}}+&hl=fr&z=14&amp;output=embed" frameborder="0" allowfullscreen></iframe>              <div class="map-wrapper-300 mb-3">

    </div>
{% endblock %}